apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 2 # Set the desired number of replicas
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: ridhimanwazir/nodejs-app:latest # Replace with your Docker image name
          ports:
            - containerPort: 5000 # Expose the port specified in your Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 5000
  type: NodePort # Use NodePort service type