---
- name: docker build and push
  hosts: local
  gather_facts: false
  become: yes  # Use sudo for copying if required

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      command: docker build -t nodejs-app .
      args:
        chdir: /var/lib/jenkins/workspace/nodejs-app

    - name: tag image
      command: docker tag nodejs-app:latest ridhimanwazir/nodejs-app:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: ridhimanwazir
        password: dckr_pat_IFZzI8goYatKSoksul8D_ipQnY8

    - name: Push image
      command: docker push ridhimanwazir/nodejs-app:latest

    - name: Run container
      command: docker run -d --name nodeapp -p 4000:4000 ridhimanwazir/nodejs-app:latest
