---
- name: deploy to k8
  hosts: k8s
  gather_facts: false
  become: yes  # Use sudo for copying if required

  tasks:
    - name: Delete Deployment
      command: kubectl delete deployment.apps/nodeapp-deployment --kubeconfig=/home/ridhimansingh/.kube/config
      ignore_errors: true

    - name: Delete service
      command: kubectl delete service/nodeapp-service --kubeconfig=/home/ridhimansingh.kube/config
      ignore_errors: true

    - name: Remove file
      command: rm -rf /home/ridhimansingh/deployment.yaml
      ignore_errors: true

    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/nodejs-app/deployment.yaml  # Assuming Jenkins workspace variable
        dest: /home/ridhimansingh

    - name: Copy service.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/nodejs-app/service.yaml  # Assuming Jenkins workspace variable
        dest: /home/ridhimansingh

    - name: Copy ingress.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/nodejs-app/ingress.yaml  # Assuming Jenkins workspace variable
        dest: /home/ridhimansingh

    - name: Apply Deployment
      command: kubectl apply --validate=false -f /home/ridhimansingh/deployment.yaml --kubeconfig=/home/ridhimansingh/.kube/config

    - name: Apply service
      command: kubectl apply --validate=false -f /home/ridhimansingh/service.yaml --kubeconfig=/home/ridhimansingh/.kube/config


